spring:
  profiles:
    active: dev

---
server:
  port:  8201

spring:
  profiles: dev
  application:
    name:  provider-service

eureka:
  client:
    service-url:
      defaultZone: http://eurka7001:7001/eureka/,http://eurka7002:7002/eureka/,http://eurka7003:7003/eureka/
---
server:
  port:  8202

spring:
  profiles:  test
  application:
    name:  provider-service

eureka:
  client:
    service-url:
      defaultZone: http://eurka7001:7001/eureka/,http://eurka7002:7002/eureka/,http://eurka7003:7003/eureka/